# See: https://www.dartlang.org/tools/pub/pubspec
name: conreality
version: 0.0.3
description: >-
  Conreality SDK for Dart
author: Conreality.org <conreality@googlegroups.com>
homepage: https://sdk.conreality.org/dart/
documentation:
dependencies:
  drylib: ^0.0.0
  grpc: ^0.6.6
  protobuf: ^0.10.4
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
  sdk: '>=2.0.0 <3.0.0'
executables:
