# See: https://www.dartlang.org/tools/pub/pubspec
name: conreality
version: 0.0.0
description: >-
  Conreality Software Development Kit (SDK) for Dart.
author: Arto Bendiken <arto@conreality.org>
homepage: https://sdk.conreality.org/dart/
documentation:
dependencies:
dev_dependencies:
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
 sdk: '>=2.0.0 <3.0.0'
executables:
